import cohere
PORCUPINE_ACCESS_KEY = "YOUR_PORCUPINE_ACCESS_KEY"
OPEN_WEATHER_API_KEY = "YOUR_OPENWEATHER_API_KEY"
SPOTIPY_CLIENT_ID = "YOUR_SPOTIFY_CLIENT_ID"
SPOTIPY_CLIENT_SECRET = "YOUR_SPOTIFY_CLIENT_SECRET"
SPOTIPY_REDIRECT_URI = "http://127.0.0.1:8888/callback"
COHERE_API_KEY = "YOUR_COHERE_API_KEY"
WAKE_WORD = "hey google"
co = cohere.Client(COHERE_API_KEY)